format = """
[░▒▓](#f5c2e7)\
$username\
[](bg:#f38ba8 fg:#f5c2e7)\
$directory\
[](fg:#f38ba8 bg:#eb7c92)\
$git_branch\
$git_status\
[](fg:#eb7c92 bg:#e6657f)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
[](fg:#e6657f bg:#e05a75)\
$time\
[ ](fg:#e05a75)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#f5c2e7 fg:#11111b"
style_root = "bg:#f5c2e7 fg:#11111b"
format = '[$user ]($style)'

[directory]
style = "bg:#f38ba8 fg:#11111b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#eb7c92 fg:#11111b"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#eb7c92 fg:#11111b"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#e6657f fg:#11111b"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#e05a75 fg:#11111b"
format = '[ $time ]($style)'
